bits ['[2]', 'grass:ls']
bits ['[4]', 'grass:ls']
bits ['[4]', 'grass:n1', 'grass:treels2']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1', 'objects:tree_mr1:V5']
bits ['[4]', 'grass:n1', 'grass:l2']
bits ['[4]', 'grass:t3', 'grass:tb']
bits ['[4]', 'wood:v_br2:4']
bits ['[4]', 'grass:n5']
bits ['[4]', 'earth:dark', 'grass:r1']
bits ['[2]', 'grass:n1', 'objects:tree_ml2:V3']
bits ['[3]', 'grass:n1']
bits ['[1]', 'grass:n1']
bits ['[3]', 'water:dark', 'grass:r1']
bits ['[3]', 'grass:n1', 'grass:l2']
bits ['[3]', 'grass:n1']
bits ['[2]', 'grass:n2']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:n1', 'grass:tr1:6']
bits ['[4]', 'grass:n1', 'grass:treels2']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[4]', 'water:dark', 'grass:tl1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:dark', 'grass:r1']
bits ['[2]', 'water:dark', 'grass:r1']
bits ['[4]', 'grass:n1']
bits ['[2,4]', 'wood:v_br2:4']
bits ['[4]', 'earth:dark', 'grass:r1']
bits ['[2]', 'grass:n3']
bits ['[3]', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[1]', 'water:dark', 'grass:l2']
bits ['[2]', 'grass:ls']
bits ['[1]', 'grass:n1']
bits ['[4]', 'water:dark', 'grass:l1']
bits ['[4]', 'grass:sarch']
bits ['[4]', 'grass:n6']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[4]', 'grass:rs']
bits ['[4]', 'grass:n2']
bits ['[4]', 'grass:ls']
bits ['[4]', 'grass:n1', 'grass:treers2', 'objects:tree_ml2:V5']
bits ['[1]', 'water:w2', 'grass:sarch']
bits ['[2]', 'water:dark', 'grass:t1']
bits ['[S4]', 'grass:bb']
bits ['[4,2]', 'grass:n1', 'grass:t2:4']
bits ['[4]', 'grass:n1']
bits ['[2]', 'earth:dark', 'grass:rj']
bits ['[2]', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[2]', 'grass:n1', 'grass:r3']
bits ['[2]', 'water:dark', 'grass:l2']
bits ['[2]', 'grass:n1', 'wood:lrs_supp:V3']
bits ['[1]', 'earth:dark', 'water:bw', 'grass:lj']
bits ['[1]', 'grass:n6']
bits ['[1]', 'grass:bb']
bits ['[2]', 'grass:rs']
bits ['[1]', 'water:dark', 'grass:t3']
bits ['[2]', 'earth:dark', 'grass:lj']
bits ['[2]', 'grass:vdark', 'earth:ac:V3']
bits ['[1]', 'grass:ms']
bits ['[4]', 'grass:n6']
bits ['[3]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:r1']
bits ['[3]', 'grass:n3']
bits ['[3]', 'water:dark', 'wood:hbr1']
bits ['[1]', 'grass:n4']
bits ['[S2.5]', 'grass:light', 'wood:st2']
bits ['[2]', 'grass:n1']
bits ['[2]', 'water:dark', 'wood:hbr3']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:lls']
bits ['[1]', 'water:t1']
bits ['[4]', 'grass:n3']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[2,4]', 'grass:n1', 'grass:t3:4', 'objects:tree_tl1:V6']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:ls']
bits ['[4]', 'grass:n1', 'objects:tree_tr2:V6']
bits ['[2]', 'grass:ls']
bits ['[2]', 'water:dark', 'grass:r2']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:bb']
bits ['[4]', 'grass:n1']
bits ['[3]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:tl2']
bits ['[3]', 'water:dark', 'grass:tr2']
bits ['[2]', 'grass:n1', 'grass:treels2']
bits ['[3]', 'water:dark', 'grass:tr1']
bits ['[3]', 'water:dark', 'grass:tr1']
bits ['[3]', 'grass:n1', 'grass:l1']
bits ['[2]', 'grass:n1', 'grass:t3:6']
bits ['[4]', 'grass:ms']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[4]', 'grass:n1', 'grass:l2']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[4]', 'grass:n1', 'objects:tree_mr1:V5']
bits ['[3]', 'grass:ms']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:n1', 'grass:r1']
bits ['[2]', 'grass:rs']
bits ['[S2]', 'grass:bb']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[S1.5]', 'earth:dark', 'wood:st1']
bits ['[1]', 'wood:v_br2']
bits ['[4]', 'water:dark', 'grass:tl1']
bits ['[4]', 'grass:n1', 'objects:tree_ml1:V5']
bits ['[1]', 'grass:n6']
bits ['[4]', 'grass:n1']
bits ['[4]', 'water:dark', 'grass:tl2']
bits ['[4]', 'grass:ms']
bits ['[4]', 'grass:ms']
bits ['[2,4]', 'grass:n1', 'grass:tr2:4']
bits ['[1]', 'grass:ms']
bits ['[4]', 'water:dark', 'grass:t3']
bits ['[2]', 'water:dark', 'grass:tr2']
bits ['[4,2]', 'grass:n1', 'grass:tr1:4']
bits ['[1]', 'grass:rs']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[2]', 'grass:n1']
bits ['[1]', 'grass:n6']
bits ['[1]', 'earth:dark', 'water:bw', 'grass:lj']
bits ['[4,2]', 'grass:n1', 'grass:tl1:4']
bits ['[1]', 'wood:v_br2']
bits ['[2]', 'grass:n1']
bits ['[3]', 'water:dark', 'wood:hbr1']
bits ['[2]', 'grass:rs']
bits ['[2]', 'water:dark', 'grass:t3']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:rs']
bits ['[3]', 'grass:tr1', 'grass:n1']
bits ['[4]', 'grass:n3']
bits ['[2]', 'earth:dark', 'grass:r3']
bits ['[2]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:r2']
bits ['[1]', 'earth:dark', 'water:bw', 'grass:rrs']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[2]', 'grass:vdark', 'earth:ac:V3']
bits ['[3]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1', 'objects:tree_mr1:V5']
bits ['[4]', 'earth:t2', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[2]', 'water:dark', 'grass:tr1']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:tr2']
bits ['[4]', 'grass:bb']
bits ['[4]', 'grass:n6']
bits ['[1]', 'water:dark', 'grass:l3']
bits ['[3]', 'grass:rs']
bits ['[2]', 'grass:n1']
bits ['[3]', 'grass:n4']
bits ['[4]', 'grass:n1']
bits ['[3]', 'water:dark', 'grass:r2']
bits ['[2]', 'grass:n1', 'objects:tree_tr2:V4']
bits ['[4]', 'grass:n1', 'grass:l1']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:l2']
bits ['[2]', 'grass:ms']
bits ['[3]', 'grass:ls']
bits ['[S3]', 'grass:st2']
bits ['[2]', 'water:dark', 'grass:r2']
bits ['[2]', 'water:dark', 'grass:t3']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:r1']
bits ['[4]', 'grass:n1']
bits ['[S1.5]', 'grass:light', 'wood:st2']
bits ['[2]', 'grass:n1']
bits ['[4,2]', 'grass:n1', 'grass:t2:4']
bits ['[2]', 'grass:n1']
bits ['[1]', 'water:dark', 'grass:t3']
bits ['[1]', 'grass:n1']
bits ['[4]', 'grass:ms']
bits ['[4]', 'grass:bb', 'grass:treels2']
bits ['[1]', 'grass:n6']
bits ['[2]', 'earth:dark', 'grass:rj']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:ls']
bits ['[1]', 'grass:ms']
bits ['[4]', 'grass:ms']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[S3.5]', 'earth:dark', 'wood:st1']
bits ['[2]', 'earth:dark', 'grass:lls']
bits ['[2]', 'water:dark', 'grass:r3']
bits ['[1]', 'water:dark', 'grass:r2']
bits ['[3]', 'grass:n1']
bits ['[2]', 'grass:n1', 'grass:treels2']
bits ['[S1.5]', 'grass:light', 'wood:st2']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:rs']
bits ['[4]', 'grass:n1', 'grass:treers2']
bits ['[2]', 'grass:n1']
bits ['[2,4]', 'grass:n1', 'grass:t2:4', 'objects:tree_tr1:V6']
bits ['[4]', 'grass:n1', 'grass:l1']
bits ['[4]', 'earth:dark', 'grass:lj']
bits ['[4]', 'wood:v_br2']
bits ['[S3.5]', 'grass:light', 'wood:st2']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:r1']
bits ['[2]', 'grass:n1']
bits ['[2]', 'grass:n1', 'objects:tree_tl2:V4']
bits ['[3]', 'grass:n1']
bits ['[1]', 'earth:dark', 'water:bw', 'grass:lj']
bits ['[3]', 'grass:n1', 'grass:l2']
bits ['[2]', 'grass:ms']
bits ['[3]', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:treers2']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:treels2']
bits ['[4]', 'earth:dark', 'grass:rj']
bits ['[2]', 'grass:rb']
bits ['[4]', 'wood:v_br2']
bits ['[1]', 'water:dark', 'wood:hbr3']
bits ['[4,2]', 'grass:tb:4']
bits ['[1]', 'water:dark', 'grass:tl2']
bits ['[2]', 'grass:ms']
bits ['[4,2]', 'grass:n1', 'grass:tr1:4']
bits ['[3]', 'grass:n6']
bits ['[4]', 'water:dark', 'grass:t2']
bits ['[2]', 'water:dark', 'grass:tl1']
bits ['[3]', 'water:dark', 'wood:hbr1']
bits ['[4]', 'grass:lb']
bits ['[1]', 'water:dark', 'grass:tr1']
bits ['[4]', 'water:dark', 'grass:l1']
bits ['[D4-2]', 'earth:drop']
bits ['[4]', 'grass:vdark', 'earth:ac:V5']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:rs']
bits ['[4]', 'earth:dark', 'grass:l1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:dark', 'grass:rj']
bits ['[1]', 'grass:vdark', 'earth:ac:V2']
bits ['[2]', 'grass:n1']
bits ['[S3.5]', 'earth:dark', 'wood:st1']
bits ['[2]', 'earth:dark', 'grass:rj']
bits ['[4]', 'grass:n1', 'grass:tl1:6']
bits ['[2]', 'grass:n1']
bits ['[4]', 'water:dark', 'grass:t3']
bits ['[2]', 'grass:n1', 'grass:r2']
bits ['[2]', 'water:dark', 'wood:hbr3']
bits ['[4,2]', 'grass:n1', 'grass:tr1:4']
bits ['[4,2]', 'grass:n1', 'grass:t2:4']
bits ['[1]', 'earth:dark', 'water:bw', 'grass:lj']
bits ['[2]', 'grass:n1', 'wood:lls_supp:V3']
bits ['[2]', 'water:dark', 'grass:tl1']
bits ['[2]', 'grass:n2']
bits ['[1]', 'grass:n1']
bits ['[1]', 'grass:n5']
bits ['[1]', 'grass:ms']
bits ['[4]', 'earth:dark', 'grass:rj']
bits ['[2]', 'grass:n1', 'grass:treers2']
bits ['[1]', 'water:dark', 'grass:t3']
bits ['[1]', 'grass:ls']
bits ['[4]', 'earth:dark', 'grass:rj']
bits ['[2]', 'earth:dark', 'grass:rj']
bits ['[2]', 'grass:n1']
bits ['[3]', 'grass:ms']
bits ['[2]', 'water:dark', 'grass:r2']
bits ['[3]', 'grass:n1']
bits ['[S2.5]', 'earth:dark', 'wood:st1']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:n1:4']
bits ['[2]', 'grass:lb']
bits ['[2]', 'grass:n1', 'grass:tr2:6']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:ms', 'objects:tree_mr1:V5']
bits ['[2,4]', 'grass:n1', 'grass:tl2:4']
bits ['[4]', 'earth:b1', 'grass:n1']
bits ['[4]', 'grass:n1', 'objects:tree_ml1:V5']
bits ['[2]', 'grass:ms']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'objects:tree_tml3:V5']
bits ['[2]', 'water:dark', 'grass:r1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'wood:v_br1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:light', 'grass:r3']
bits ['[4]', 'water:dark', 'grass:t3']
bits ['[2]', 'water:dark', 'grass:l3']
bits ['[S3]', 'grass:bb']
bits ['[2]', 'grass:n1', 'grass:treers2']
bits ['[3]', 'water:dark', 'grass:r2']
bits ['[3]', 'water:dark', 'grass:tl1']
bits ['[2]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:l3']
bits ['[2]', 'grass:n1', 'grass:t1:6']
bits ['[2]', 'grass:n2']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:ls']
bits ['[4]', 'grass:light', 'grass:r3']
bits ['[4]', 'water:dark', 'grass:l1']
bits ['[4]', 'water:dark', 'grass:t3']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[2]', 'water:dark', 'grass:r3']
bits ['[4]', 'grass:n1', 'objects:tree_tr1:V6']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[S1.5]', 'earth:dark', 'wood:st1']
bits ['[2]', 'grass:n1']
bits ['[2]', 'earth:dark', 'grass:lls']
bits ['[1]', 'earth:dark', 'grass:lls']
bits ['[4]', 'water:dark', 'grass:l2']
bits ['[2]', 'earth:dark', 'grass:rrs']
bits ['[1]', 'grass:n1']
bits ['[4]', 'grass:ms']
bits ['[4]', 'grass:n6']
bits ['[1]', 'grass:ms']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:n6']
bits ['[2]', 'grass:n1']
bits ['[2,4]', 'grass:n1', 'wood:hbr2:4']
bits ['[1]', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[1]', 'wood:v_br1']
bits ['[4,2]', 'grass:n1', 'grass:t3:4']
bits ['[4]', 'grass:rs']
bits ['[2]', 'grass:sarch']
bits ['[4]', 'grass:n1']
bits ['[4,3]', 'grass:n1', 'grass:tr1:4']
bits ['[2]', 'grass:n1']
bits ['[4,3]', 'grass:n1', 'grass:t2:4']
bits ['[2]', 'earth:dark', 'grass:rj']
bits ['[2]', 'grass:ms']
bits ['[S2]', 'grass:st2']
bits ['[2]', 'water:dark', 'grass:r3']
bits ['[4]', 'earth:dark', 'grass:l1']
bits ['[1]', 'grass:ms']
bits ['[4]', 'grass:rs']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1', 'objects:tree_tr1:V6']
bits ['[4]', 'grass:n1', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[4,2]', 'grass:n1', 'grass:t1:4']
bits ['[4]', 'grass:n1', 'grass:treers2']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:light', 'grass:t2']
bits ['[1]', 'grass:lb']
bits ['[4,3]', 'grass:n1', 'grass:tr1:4']
bits ['[4]', 'grass:n2']
bits ['[2]', 'grass:n1']
bits ['[3]', 'grass:rb']
bits ['[2]', 'grass:n5', 'objects:tree_mr2:V3']
bits ['[4]', 'grass:n1', 'grass:l3']
bits ['[2]', 'earth:dark', 'water:bw', 'grass:l2']
bits ['[4]', 'earth:dark', 'grass:rj']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:dark', 'grass:l1']
bits ['[3]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:r3']
bits ['[4]', 'grass:n1']
bits ['[S1]', 'grass:st2']
bits ['[1]', 'grass:n2']
bits ['[S2]', 'grass:bb']
bits ['[1]', 'grass:tb']
bits ['[4]', 'grass:n4']
bits ['[4]', 'grass:n1', 'objects:tree_tl1:V6']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:n6']
bits ['[1]', 'grass:n1']
bits ['[1]', 'grass:n1']
bits ['[S1]', 'grass:st2']
bits ['[4]', 'grass:ls', 'objects:tree_ml1:V5']
bits ['[4]', 'earth:dark', 'grass:rj']
bits ['[2]', 'water:dark', 'grass:t2']
bits ['[4]', 'grass:n4:4']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n5']
bits ['[S3]', 'grass:st2']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:r2']
bits ['[2]', 'grass:n4']
bits ['[3]', 'water:dark', 'grass:r3']
bits ['[1]', 'water:dark', 'grass:l1']
bits ['[2]', 'water:dark', 'grass:rrs']
bits ['[1]', 'water:dark', 'grass:r2']
bits ['[2]', 'grass:n1']
bits ['[3]', 'water:dark', 'grass:t2']
bits ['[2]', 'grass:n5']
bits ['[2]', 'grass:n1']
bits ['[4,2]', 'grass:n1', 'grass:t3:4']
bits ['[2]', 'grass:ms']
bits ['[4]', 'grass:n6']
bits ['[2]', 'grass:ls']
bits ['[4]', 'grass:n1']
bits ['[1]', 'water:dark', 'wood:hbr2']
bits ['[4]', 'grass:n1']
bits ['[2]', 'water:dark', 'grass:r2']
bits ['[4]', 'wood:v_br1']
bits ['[4]', 'grass:n1']
bits ['[3]', 'grass:n4']
bits ['[4]', 'grass:rb']
bits ['[3]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[3]', 'water:dark', 'grass:r1']
bits ['[2]', 'earth:dark', 'water:bw', 'grass:l2']
bits ['[2]', 'water:dark', 'grass:t1']
bits ['[4]', 'grass:n1', 'grass:l1']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:l1']
bits ['[4]', 'grass:n1', 'grass:treels2']
bits ['[3]', 'grass:n1:3']
bits ['[S3.5]', 'grass:light', 'wood:st2']
bits ['[2]', 'grass:rs']
bits ['[2]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:r2']
bits ['[4]', 'earth:dark', 'grass:l1']
bits ['[2]', 'grass:rs']
bits ['[2]', 'grass:n1']
bits ['[2,4]', 'grass:n1', 'wood:hbr1:4']
bits ['[4]', 'grass:n1']
bits ['[2]', 'grass:n1']
bits ['[2]', 'grass:t3', 'objects:tree_ml1:V3']
bits ['[1]', 'grass:n1']
bits ['[1]', 'grass:n1']
bits ['[1]', 'grass:n1']
bits ['[4]', 'grass:n6']
bits ['[4]', 'grass:n1']
bits ['[4]', 'earth:light', 'water:bw', 'grass:tl2']
bits ['[1]', 'grass:n1']
bits ['[4]', 'grass:n1', 'grass:r1']
bits ['[S4]', 'grass:bbrs']
bits ['[2]', 'water:dark', 'water:dark', 'grass:r1']
bits ['[4]', 'grass:n1', 'grass:rrs']
bits ['[1]', 'water:dark', 'grass:tr2']
bits ['[3]', 'grass:n1']
